# Generated by Django 2.2.4 on 2019-08-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
